name: Filter Loss Games from bijiy.pgn

on:
  workflow_dispatch:  # manual trigger
  push:
    paths:
      - bijiy.pgn       # auto trigger when bijiy.pgn changes

jobs:
  filter-losses:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install python-chess
      run: pip install python-chess

    - name: Filter losses from bijiy.pgn
      run: |
        python - <<EOF
        import chess.pgn

        infile = open("bijiy.pgn", "r", encoding="utf-8")
        outfile = open("bijiy2.pgn", "w", encoding="utf-8")

        while True:
            game = chess.pgn.read_game(infile)
            if game is None:
                break
            result = game.headers.get("Result", "")
            white = game.headers.get("White", "")
            black = game.headers.get("Black", "")
            if (white == "bijiy" and result == "0-1") or (black == "bijiy" and result == "1-0"):
                continue  # skip loss
            print(game, file=outfile, end="\n\n")

        infile.close()
        outfile.close()
        EOF

    - name: Upload bijiy2.pgn
      uses: actions/upload-artifact@v4
      with:
        name: bijiy2-pgn
        path: bijiy2.pgn
