name: Create Polyglot Book
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Polyglot
        run: |
          sudo apt-get update
          sudo apt-get install -y polyglot

      - name: Build Backup.bin
        run: |
          # -min-score 0 and -min-game 1 ensure tiny books aren’t filtered
          polyglot make-book \
            -pgn backup.pgn \
            -bin Backup.bin \
            -max-ply 10 \
            -min-score 0 \
            -min-game 1

      - name: Upload Backup.bin
        uses: actions/upload-artifact@v4
        with:
          name: Backup.bin
          path: Backup.bin
