name: Run Stockfish321 Notebook Commands on Kaggle

on:
  schedule:
    # Runs every 59 minutes
    - cron: '*/59 * * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    env:
      KAGGLE_KEY_JSON: ${{ secrets.KAGGLE_KEY_JSON }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Kaggle CLI
      run: |
        python -m pip install --upgrade pip
        pip install kaggle nbformat

    - name: Authenticate Kaggle
      run: |
        mkdir -p ~/.kaggle
        echo "${KAGGLE_KEY_JSON}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Append commands from cmd.txt to existing notebook
      run: |
        python - <<EOF
import nbformat as nbf

# Load your existing notebook
nb = nbf.read("Stockfish321.ipynb", as_version=4)

# Add each line from cmd.txt as a new code cell
with open("cmd.txt") as f:
    for line in f:
        line = line.strip()
        if line:
            nb.cells.append(nbf.v4.new_code_cell(line))

# Save notebook
nbf.write(nb, "Stockfish321.ipynb")
EOF

    - name: Push notebook to Kaggle
      run: |
        kaggle kernels push -p . --kernel Stockfish321 --quiet

    - name: Run notebook on Kaggle and get output
      run: |
        kaggle kernels output Stockfish321 -p /tmp/stockfish_output --quiet
