name: Join Lichess Tournament

on:
  workflow_dispatch:

jobs:
  join:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Join Lichess tournament
        env:
          TOR: ${{ secrets.TOR }}
          TMT_ID: ${{ secrets.TMT_ID }}  # Optional, or hardcoded in script
        run: python3 join_tournament.py
