name: Automate Kaggle Notebook Stockfish321

on:
  schedule:
    - cron: '*/59 * * * *' # Every 59 minutes
  workflow_dispatch:

jobs:
  run-cmds-on-kaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install kaggle nbformat

      - name: Setup kaggle.json
        run: |
          mkdir -p ~/.kaggle
          cp kaggle.json ~/.kaggle/
          chmod 600 ~/.kaggle/kaggle.json

      - name: Generate, Push, and Execute Notebook
        run: python auto.py
