name: Make White Opening Book

on:
  workflow_dispatch:  # run manually from the Actions tab

jobs:
  make-white-book:
    runs-on: ubuntu-latest

    steps:
      # 1 – Fetch your repository (white.pgn must be in the repo root)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2 – Install Polyglot 2.0.4 from Ubuntu repos
      - name: Install Polyglot
        run: |
          sudo apt-get update
          sudo apt-get install -y polyglot      # provides polyglot 2.0.4

      # 3 – Build white.bin from white.pgn
      - name: Build white.bin
        run: |
          polyglot make-book \
            -pgn white.pgn \        # input PGN
            -bin white.bin \        # output book
            -max-ply 40 \           # keep first 20 full moves
            -min-game 2             # discard lines seen only once

      # 4 – Upload the finished book
      - name: Upload white.bin
        uses: actions/upload-artifact@v4
        with:
          name: white.bin           # artifact label
          path: white.bin
