name: Make White Opening Book           # Workflow title in the Actions tab

on:
  workflow_dispatch:                    # Manual trigger (click “Run workflow”)

jobs:
  make-white-book:
    runs-on: ubuntu-latest              # Free Ubuntu runner on every execution

    steps:
    # 1️⃣ Pull the repo so we have whiter.pgn
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Get the Polyglot utility from Ubuntu’s package repo
    - name: Install Polyglot
      run: |
        sudo apt-get update
        sudo apt-get install -y polyglot

    # 3️⃣ Build the opening book
    - name: Build white.bin from whiter.pgn
      run: |
        # -pgn   → input PGN (your loss-free file)
        # -bin   → output Polyglot book
        # -min-game 1 keeps every move that occurred at least once
        polyglot make-book -pgn whiter.pgn -bin white.bin -min-game 1

    # 4️⃣ Make the resulting book downloadable from the workflow page
    - name: Upload white.bin
      uses: actions/upload-artifact@v4
      with:
        name: white-book                # Artifact name shown in UI
        path: white.bin                 # File to upload
