name: Make White Opening Book

on:
  workflow_dispatch:

jobs:
  make-white-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Polyglot
        run: |
          sudo apt-get update
          sudo apt-get install -y polyglot

      - name: Build white.bin (up to 80 plies = 40 moves)
        run: |
          polyglot make-book -pgn white.pgn -bin white.bin -min-game 2 -max-ply 100

      - name: Upload black.bin
        uses: actions/upload-artifact@v4
        with:
          name: white.bin
          path: white.bin
