name: Make Opening Book

on:
  workflow_dispatch:
    inputs:
      pgn_file:                   # Input 1: PGN name without extension
        description: "Enter PGN base name (e.g. ho for ho.pgn)"
        required: true
        default: ""
      bin_file:                   # Input 2: BIN name without extension
        description: "Enter BIN base name (e.g. peu for peu.bin)"
        required: true
        default: ""

jobs:
  make-book:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pull the repo so we have PGN files
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Polyglot
      - name: Install Polyglot
        run: |
          sudo apt-get update
          sudo apt-get install -y polyglot

      # 3️⃣ Build the opening book
      - name: Build BIN from PGN
        run: |
          pgn_input="${{ github.event.inputs.pgn_file }}.pgn"
          bin_output="${{ github.event.inputs.bin_file }}.bin"
          echo "Building $bin_output from $pgn_input..."
          polyglot make-book -pgn "$pgn_input" -bin "$bin_output" -min-game 1

      # 4️⃣ Upload the resulting BIN
      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.bin_file }}-book
          path: ${{ github.event.inputs.bin_file }}.bin
